ARG dyninst_base=ghcr.io/dyninst/dyninst-ubuntu-20.04:latest
FROM ${dyninst_base}

# docker build --build-arg dyninst_base=ghcr.io/dyninst/dyninst-ubuntu-20.04:latest -f Dockerfile.test -t dyninst-test .

# TODO update code here via dyninst source, if needed
# COPY . /code

# Add testing script to run
COPY ./test.sh /opt/dyninst-env/test.sh

# Clone dyninst tests
RUN git clone https://github.com/dyninst/testsuite /opt/testsuite

# Previous WORKDIR, just to be careful - reinstall dyninst if needed
# Thenbuild and run the test suite
WORKDIR /opt/dyninst-env
RUN /bin/bash test.sh
